### PR TITLE
Support recurring events from .ics

### LINKED ISSUE #94: Support recurring events from .ics
Need to try implementing recurring events (not to be confused with multiday events) that are read from .ics files.

### PR DESCRIPTION
**Pull request by janusfil**
This implementation will generate reccuring events based on `RRULE` in ics file. It will generate infinity events only for 1 year, so if you want to see more events in next years you need to reload data in that year (with `Q`)
note: please feel free to comment and repair me or offer a better solution, I am not python developer :innocent:

Closes #94

### CODE REVIEW

**Comment by anufrievroman** [comment]
Thank you for working on this! I'll check and test as soon as I can.

**Comment by anufrievroman** [comment]
Thank you again for your contribution! I seem to work fine. Ideally, I'd prefer all the `rrule` stuff to be read and converted to internal fields like `repetitions` and `frequency` already in the `loaders.py`, so that we don't carry those field through the program. However, I guess it's not always possible if the `rrule` is more complicated than "repeat every X for N times". So, let's keep it like that for now, as it works.

**Comment by anufrievroman** [comment]
By the way, while we are at it, may I ask what is exactly `exdate` and what it contains?

**Comment by janusfil** [comment]
Yep, my first try was exactly converting to internal fields but as you guessed, real events can be more complicated. You can have specific days for recurring event and you can have interval between them (each 2 weeks instead of each week). And `exdate` is for exclude specific date from repetition. (If you do remove on recurring event in google calendar and choose **Only this event**)

**Comment by anufrievroman** [comment]
I see, okay, thank you for the explanation !

**Pull request merged**
